### ISSUE TITLE
Read Test and Train Data

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/Machine-Learning#1]
Write a python script to read both csv files.

**Comment by Jaggu-123** [comment]
@opencodebot claim

**Comment by Jaggu-123** [comment]
@opencodebot claim

**Comment by rishuraj3152** [comment]
@opencodebot claim

**Comment by rishuraj3152** [comment]
@opencodebot claim

**Comment by rishuraj3152** [comment]
There is a "open" tag in this issue but still i m unable to claim. you need to modify it.
