### ISSUE TITLE
Read data from .csv files

### ISSUE THREAD

**Issue by ambuj-krishna-agrawal** [opencodeiiita/Machine-Learning#3]
From the given dataset, train.csv and test.csv, read the features and labels into separate variables i.e into train_data_x, train_y, test_data_x, test_y.

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ashish4321** [comment]
@aka-jumba No accept invitation link has been sent. I claimed it twice

**Comment by ambuj-krishna-agrawal** [comment]
@ashish4321 you are assigned the issue.

**Comment by ashish4321** [comment]
@aka-jumba Review the PR
