### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by ambuj-krishna-agrawal** [opencodeiiita/Machine-Learning#4]
Visualize the train and test data using individual histogram, scatter and box plots in matplotlib.

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ambuj-krishna-agrawal** [comment]
@ashish4321 you are assigned the issue.

**Comment by mohitjain20** [comment]
@opencodebot claim
