### ISSUE TITLE
make cost_and_grad function

### ISSUE THREAD

**Issue by ambuj-krishna-agrawal** [opencodeiiita/Machine-Learning#7]
cost_and_grad function takes in X, Y and theta ( initialize it with zero vector of required shape) and outputs the cost (or error) and grad vector( derivative of cost function with respect to theta initialized to zero vector).
Cost function should be that of average squared difference.

**Comment by ashish4321** [comment]
@opencodbot claim

**Comment by kesari007** [comment]
@opencodebot claim

**Comment by kesari007** [comment]
@opencodebot claim
